# Generated by Django 4.2.3 on 2023-08-03 01:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacto', '0002_quienessomos'),
    ]

    operations = [
        migrations.DeleteModel(
            name='QuienesSomos',
        ),
    ]
