# Generated by Django 4.2.3 on 2023-07-19 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_alter_post_imagen_articulo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articulo',
            name='imagen',
            field=models.ImageField(blank=True, default='articulo/default_articulo.jpg', null=True, upload_to='articulo'),
        ),
        migrations.AlterField(
            model_name='post',
            name='imagen',
            field=models.ImageField(blank=True, default='static/post_default.png', null=True, upload_to='post'),
        ),
    ]
