# Generated by Django 4.2.3 on 2023-07-20 22:49
from django.db import migrations, models
from apps.posts.models import get_random_avatar_filename  # Asegúrate de tener la importación correcta aquí

class Migration(migrations.Migration):
    dependencies = [
        ('posts', '0003_alter_articulo_imagen_alter_post_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='articulo',
            name='nickname',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='articulo',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to=get_random_avatar_filename),
        ),
    ]

