# Generated by Django 4.2.3 on 2023-07-20 22:55

from django.db import migrations, models
from apps.posts.models import get_random_avatar_filename

class Migration(migrations.Migration):
    dependencies = [
        ('posts', '0004_articulo_avatar_articulo_nickname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articulo',
            name='avatar',
            field=models.ImageField(blank=True, default=get_random_avatar_filename, null=True, upload_to='avatar1_default'),
        ),
    ]
