# Generated by Django 4.2.3 on 2023-07-20 23:15

import apps.posts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_alter_articulo_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articulo',
            name='avatar',
            field=models.ImageField(blank=True, default=apps.posts.models.get_random_avatar_filename, null=True, upload_to=apps.posts.models.get_random_avatar_filename),
        ),
        migrations.AlterField(
            model_name='articulo',
            name='nickname',
            field=models.CharField(default='Sin NickName', max_length=30),
            preserve_default=False,
        ),
    ]
