# Generated by Django 4.2.3 on 2023-07-20 23:20

import apps.posts.models
from django.db import migrations, models
import functools


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_alter_articulo_avatar_alter_articulo_nickname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articulo',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to=functools.partial(apps.posts.models.get_random_avatar_filename, *(), **{'filename': ''})),
        ),
        migrations.AlterField(
            model_name='articulo',
            name='nickname',
            field=models.CharField(default='Sin Nickname', max_length=30),
        ),
    ]
