# Generated by Django 4.2.3 on 2023-07-20 23:27

import apps.posts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0007_alter_articulo_avatar_alter_articulo_nickname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articulo',
            name='avatar',
            field=models.ImageField(blank=True, default='articulo/avatar/avatar3_default.jpg', null=True, upload_to=apps.posts.models.get_random_avatar_filename),
        ),
    ]
