# Generated by Django 4.2.3 on 2023-07-21 12:28

import apps.posts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0008_alter_articulo_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articulo',
            name='avatar',
            field=models.ImageField(blank=True, default=apps.posts.models.default_avatar, null=True, upload_to=apps.posts.models.get_random_avatar_filename),
        ),
    ]
